version: '3.8'

services:
  # Redis (for caching)
  redis:
    image: redis:7-alpine
    container_name: catalyst-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - catalyst-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # News Service
  news:
    build:
      context: ./services/news
      dockerfile: Dockerfile
    container_name: catalyst-news
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEWS_API_KEY: ${NEWS_API_KEY}
    ports:
      - "5008:5008"
    volumes:
      - ./services/news/config:/app/config:ro  # Read-only config mount
      - news_logs:/app/logs
    networks:
      - catalyst-network
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis_data:
  news_logs:

networks:
  catalyst-network:
    driver: bridge
