version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: catalyst-postgres
    environment:
      POSTGRES_DB: catalyst_trading
      POSTGRES_USER: catalyst
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - catalyst-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catalyst"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:7-alpine
    container_name: catalyst-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - catalyst-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # News Service ONLY
  news:
    build:
      context: ./services/news
      dockerfile: Dockerfile
    container_name: catalyst-news
    environment:
      DATABASE_URL: postgresql://catalyst:${DB_PASSWORD}@postgres:5432/catalyst_trading
      NEWS_API_KEY: ${NEWS_API_KEY}
      BENZINGA_API_KEY: ${BENZINGA_API_KEY}
    ports:
      - "5008:5008"
    volumes:
      - ./services/news:/app
      - news_logs:/app/logs
    networks:
      - catalyst-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  news_logs:

networks:
  catalyst-network:
    driver: bridge

