# Pattern Detection Configuration
patterns:
  hammer:
    confidence_threshold: 0.65
    body_ratio: 0.3
    wick_ratio: 2.0
  
  doji:
    confidence_threshold: 0.55
    body_ratio: 0.1
    
  engulfing:
    confidence_threshold: 0.70
    volume_confirmation: true

timeframes:
  - "1m"
  - "5m"
  - "15m"
  - "1h"
  - "1d"
